server:
  port: 8082
spring:
  data:
    mongodb:
      host: host.docker.internal
      port: 27017
      authentication-database: admin
      username: admin
      password: admin
      database: antsprod